name: "Run integration tests"
description: "Run Inspektor Gadget integration tests"

inputs:
  registry:
    description: 'Server address of registry where integration tests container image will be pushed'
    required: false
  username:
    description: 'Username used to log against the registry'
    required: false
  password:
    description: 'Password or access token used to log against the registry'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set IMAGE_TAG
      shell: bash
      run: |
        TMP1=${GITHUB_REF#*/}
        TMP2=${TMP1#*/}
        IMAGE_TAG=${TMP2//\//-}
        if [ "$IMAGE_TAG" = "main" ]; then
            IMAGE_TAG="latest"
        fi
        echo IMAGE_TAG=$IMAGE_TAG >> $GITHUB_ENV
    - name: Get kubectl-gadget-linux-amd64.tar.gz from artifact.
      uses: actions/download-artifact@v2
      with:
        name: kubectl-gadget-linux-amd64-tar-gz
        path: /home/runner/work/inspektor-gadget/
    - name: Integration tests
      shell: bash
      run: |
        echo "Using IMAGE_TAG=$IMAGE_TAG"

        tar zxvf /home/runner/work/inspektor-gadget/kubectl-gadget-linux-amd64.tar.gz
        mv kubectl-gadget kubectl-gadget-linux-amd64

        # Notify the ig-integration-tests container that the workflow run
        # was cancelled so that it can undeploy Inspektor Gadget and SPO
        cleanup() { \
            echo "Workflow run was cancelled. Signal: $1"; \
            trap - SIGINT SIGTERM SIGHUP; \
            docker kill --signal="SIGINT" ig-integration-tests; \
            docker wait ig-integration-tests; \
            exit 0; \
        }

        trap 'cleanup SIGINT' SIGINT
        trap 'cleanup SIGTERM' SIGTERM
        trap 'cleanup SIGHUP' SIGHUP

        TESTS_DOCKER_ARGS="-e KUBECONFIG=/root/.kube/config -v /home/runner/.kube:/root/.kube -v /home/runner/work/_temp/.minikube:/home/runner/work/_temp/.minikube" \
            make -C integration build test

        sed -i "s/latest/$IMAGE_TAG/g" integration/gadget-integration-tests-job.yaml
    - name: Add integration asset as artifact.
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@master
      with:
        name: integration-asset
        path: /home/runner/work/inspektor-gadget/inspektor-gadget/integration/gadget-integration-tests-job.yaml
    - name: Login to Container Registry
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Push Integration Test Image
      shell: bash
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        make -C integration push
